TicketsBooking/Models/ChangePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TicketsBooking.Models
{
    public class ChangePasswordViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

TicketsBooking/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TicketsBooking.BLL.Interfaces;
using TicketsBooking.DAL.Entities;
using TicketsBooking.DAL.Interfaces;
using TicketsBooking.DTO.Ticket;
using TicketsBooking.Models;
using X.PagedList;

namespace TicketsBooking.Controllers
{
    public class TicketController : Controller
    {
        private IServiceTicket _ticketService;
        private IOrderService _orderService;
        private IServiceFlight _flightService;
        private IServiceUser _serviceUser;
        private IUnitOfWork _unitOfWork;
        public TicketController(IUnitOfWork unitOfWork, IServiceTicket ticketService, IOrderService orderService, IServiceFlight serviceFlight, IServiceUser serviceUser) : base()
        {
            _ticketService = ticketService;
            _orderService = orderService;
            _flightService = serviceFlight;
            _serviceUser = serviceUser;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Search(FlightViewModel flightViewModel)
        {
            var flights = _flightService.GetAll().Where(t => t.LocationFrom == flightViewModel.cityFrom).
                Where(t => t.LocationTo == flightViewModel.cityTo).
                Where(t => t.FlightDepartmentDate.Year == flightViewModel.dateTime.Year).
                Where(t => t.FlightDepartmentDate.Month == flightViewModel.dateTime.Month).
                Where(t => t.FlightDepartmentDate.Day == flightViewModel.dateTime.Day);

            //flights = flights.OrderBy(t => t.Tickets.Max(k=>k.Price)).ToList();

            var tickets = new List<TicketViewModel>();
            foreach (var iteam in flights)
            {
                var likes = _unitOfWork.LikeRepository.GetAll().Where(t => t.FlightId == iteam.Id);

                var listTicket = _unitOfWork.TicketRepository.GetQuery().Include(t => t.Basket).Where(t => t.Basket == null).Where(t => t.FlightId == iteam.Id);

                foreach (var ticket in listTicket)
                {
                    if (ticket.FlightId == iteam.Id)
                    {
                        var viewTicket = new TicketViewModel()
                        {
                            Id = ticket.Id,
                            Price = ticket.Price,
                            FlightArrivingDate = iteam.FlightArrivingDate,
                            FlightDepartmentDate = iteam.FlightDepartmentDate,
                            LocationFrom = iteam.LocationFrom,
                            LocationTo = iteam.LocationTo,
                            CollLike = likes.Count()
                        };
                        tickets.Add(viewTicket);
                    }

                }
            }
            if (tickets.Count != 0)
            {
                //tickets = tickets.OrderBy(t => t.Price).ThenBy(t => t.FlightArrivingDate).ToList();
                //return View(new ListObj { ticketViews = tickets } );
                return View(tickets);
            }
            return View();
        }

        public IActionResult AddToCart(int id)
        {

            _orderService.AddItemToBasket(User.Identity.Name, id.ToString());

            return RedirectToAction("Index");
        }


        public IActionResult GetAllTickets(int? pg)
        {
            int pageSize = 3;
            int pageNumber = (pg ?? 1);
            var flights = _unitOfWork.FlightRepository.GetQuery().Include(t => t.Tickets);
            var tickets = new List<TicketViewModel>();
            foreach (var iteam in flights)
            {
                foreach (var ticket in iteam.Tickets)
                {
                    var viewTicket = new TicketViewModel()
                    {
                        Id = ticket.Id,
                        Price = ticket.Price,
                        FlightArrivingDate = iteam.FlightArrivingDate,
                        FlightDepartmentDate = iteam.FlightDepartmentDate,
                        LocationFrom = iteam.LocationFrom,
                        LocationTo = iteam.LocationTo
                    };

                    tickets.Add(viewTicket);
                }
            }

            var listTickets = tickets.ToPagedList(pageNumber, pageSize);

            ViewBag.listTickets = listTickets;

            return View();
        }

        public IActionResult SortByDate (int? pg)
        {
            int pageSize = 3;
            int pageNumber = (pg ?? 1);
            var flights = _unitOfWork.FlightRepository.GetQuery().Include(t => t.Tickets);
            var tickets = new List<TicketViewModel>();
            foreach (var iteam in flights)
            {
                foreach (var ticket in iteam.Tickets)
                {
                    var viewTicket = new TicketViewModel()
                    {
                        Id = ticket.Id,
                        Price = ticket.Price,
                        FlightArrivingDate = iteam.FlightArrivingDate,
                        FlightDepartmentDate = iteam.FlightDepartmentDate,
                        LocationFrom = iteam.LocationFrom,
                        LocationTo = iteam.LocationTo
                    };

                    tickets.Add(viewTicket);
                }
            }

            var listTickets = tickets.OrderBy(t => t.FlightDepartmentDate).ToList();
            var listTicketsResult = listTickets.ToPagedList(pageNumber, pageSize);
            ViewBag.listTickets = listTicketsResult;

            return View();
        }

        public IActionResult AddLike(int id)
        {
            var tiket = _unitOfWork.TicketRepository.GetAll().Where(t => t.Id == id).FirstOrDefault();
            var like = _unitOfWork.LikeRepository.GetAll().Where(t => t.UserEmail == User.Identity.Name).Where(k=>k.FlightId == tiket.FlightId).FirstOrDefault();
            if (like == null)
            {
                Like likeDTO = new Like
                {
                    UserEmail = User.Identity.Name,
                    FlightId = tiket.FlightId
                };
                _unitOfWork.LikeRepository.Create(likeDTO);
            }
            else
            {
                _unitOfWork.LikeRepository.Delete(like.Id.ToString());
            }
            return RedirectToAction("Index");
        }


    }
}

TicketsBooking/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TicketsBooking.DAL.Entities;
using TicketsBooking.Models;

namespace TicketsBooking.Controllers
{
    public class UsersController : Controller
    {
        UserManager<User> _userManager;
        private IMapper _mapper;
        public UsersController(UserManager<User> userManager, IMapper mapper)
        {
            _userManager = userManager;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var user = _userManager.Users.Where(t => t.UserName == User.Identity.Name).First();
            var editView = _mapper.Map<EditUserViewModel>(user);
            return View(editView);
        }

        [HttpPost]
        public async Task<IActionResult> Index(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(_userManager.Users.Where(t=>t.UserName == User.Identity.Name).First().Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.LastName = model.LastName;
                    user.FirstName = model.FirstName;

                    var result = await _userManager.UpdateAsync(user);


                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            return View(model);
        }

        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    var _passwordValidator =
                        HttpContext.RequestServices.GetService(typeof(IPasswordValidator<User>)) as IPasswordValidator<User>;
                    var _passwordHasher =
                        HttpContext.RequestServices.GetService(typeof(IPasswordHasher<User>)) as IPasswordHasher<User>;

                    IdentityResult result =
                        await _passwordValidator.ValidateAsync(_userManager, user, model.Password);
                    if (result.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, model.Password);
                        await _userManager.UpdateAsync(user);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Users not found");
                }
            }
            return View(model);
        }

    }
}

TicketsBooking/Views/Users/ChangePassword.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model TicketsBooking.Models.ChangePasswordViewModel

<link rel="stylesheet" href="~/css/main.css">
@*<script src="~/js/main.min.js"></script>*@
<title>Sign up</title>

@if (User.IsInRole("Admin"))
{
    <header class="header">
        <div class="container">
            <a class="header_logotype active" href="/">
                W<span>G</span>
            </a>
            <nav class="header_menu">
                <div class="header_burger">
                    <div class="header_burger_item"></div>
                </div>
                <ul class="header_menu-list">
                    <li class="header_menu-item">
                        <a class="header_menu-item--link" href="@Url.Action("Index", "Ticket")">Tickets</a>
                    </li>
                    <li class="header_menu-item">
                        <a class="header_menu-item--link" href="#">Users</a>
                    </li>
                    <li class="header_menu-item">
                        <a class="header_menu-item--link" href="">Add Ticket</a>
                    </li>

                    <li class="header_menu-item">
                        <a class="header_menu-item--link" href=""> @User.Identity.Name </a>
                    </li>

                </ul>
            </nav>
            <div class="header_buttons">
         
                <a class="header_buttons-login" href="/Account/LogOff">
                    <span>Logout</span>
                </a>
            </div>
        </div>
    </header>
}

@if (!User.IsInRole("Admin"))
{
    <header class="header">
        <div class="container">
            <a class="header_logotype active" href="/">
                W<span>G</span>
            </a>
            <nav class="header_menu">
                <div class="header_burger">
                    <div class="header_burger_item"></div>
                </div>
                <ul class="header_menu-list">
                    <li class="header_menu-item">
                        <a class="header_menu-item--link" href="@Url.Action("Index", "Ticket")">Tickets</a>
                    </li>

                    <li class="header_menu-item">
                        <a class="header_menu-item--link" href="#">Companies</a>
                    </li>
                    <li class="header_menu-item">
                        <a class="header_menu-item--link" href="/Home/About">About</a>
                    </li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="header_menu-item">
                            <a class="header_menu-item--link" href="/Users/Index"> @User.Identity.Name </a>
                        </li>
                        <li class="header_menu-item">
                            <a class="header_menu-item--link" href="/HistoryBought/Index"> History </a>
                        </li>
                    }
                </ul>
            </nav>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="header_buttons">
                    <a class="header_buttons-basket" href="/Cart/Index">
                        <img src="~/img/icon/basket.svg" alt="">
                    </a>
                    <a class="header_buttons-login" href="/Account/LogOff">
                        <span>Logout</span>
                    </a>
                </div>
            }
        </div>
    </header>
}

<div class="login-page container">
    <div class="form-wrapper ">
        <div class="form-wrapper_title-block">
            <span class="form-wrapper_title-text">Edit</span>
        </div>
        <form class="form-block" id="signup-form" method="post" asp-action="ChangePassword" asp-controller="Users">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email"
                       type="email"
                       readonly
                       class="form-group-input"
                       name="Email"
                       value="@Model.Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label" asp-for="Password">Password</label>
                <input type="password"
                       class="form-group-input"
                       name="Password"
                       asp-for="Password"
                       value="">
                <span asp-validation-for="Password"></span>
            </div>
            <input type="submit" class="form-group-button" value="Change Password →" />
        </form>
    </div>
</div>

<footer class="footer">
    <div class="container footer-wrapper">
        <div class=" main_block-header1 footer-logotype">
            WeGo
        </div>
        <div class="footer-menu">
            <div class="footer-title">Links</div>
            <nav class="footer-menu-nav">
                <ul>
                    <li>
                        <a href="#">Tickets</a>
                    </li>
                    <li>
                        <a href="#">Special</a>
                    </li>
                    
                    <li>
                        <a href="#">About</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="footer-contact">
            <div class="footer-title">Contact</div>
            <div class="footer-contact-wrapper">
                <a class="footer-contact-col-line" target="_blank" href="tel:+380931234567">+380931234567</a>
                <a class="footer-contact-col-line" target="_blank" href="test@gmail.com">test@gmail.com</a>

            </div>
        </div>
        <div class="footer-socials">
            <div class="footer-title">Socials</div>
            <div class="footer-socials-wrapper">
                <a href="#" title="Facebook"
                   class="footer-socials-item"
                   target="_blank">
                    @* <img src="" class="footer_socials-item--image" alt="Facebook"> *@
                </a>
                <a href="#" title="Twitter" class="footer-socials-item" target="_blank">
                    @* <img src="" class="footer_socials-item--image" alt="Twitter"> *@
                </a>
                <a href="#" title="Instagram" class="footer-socials-item" target="_blank">
                    @* <img src="" class="footer_socials-item--image" alt="Twitter"> *@
                </a>
            </div>
        </div>
    </div>
</footer>

TicketsBooking/Views/Users/Index.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model TicketsBooking.Models.EditUserViewModel

<link rel="stylesheet" href="~/css/main.css">
@*<script src="~/js/main.min.js"></script>*@
<title>Sign up</title>
<header class="header">
    <div class="container">
        <a class="header_logotype active" href="/">
            W<span>G</span>
        </a>
        <nav class="header_menu">
            <div class="header_burger">
                <div class="header_burger_item"></div>
            </div>
            <ul class="header_menu-list">
                <li class="header_menu-item">
                    <a class="header_menu-item--link" href="@Url.Action("Index", "Ticket")">Tickets</a>
                </li>

                <li class="header_menu-item">
                    <a class="header_menu-item--link" href="#">Companies</a>
                </li>
                <li class="header_menu-item">
                    <a class="header_menu-item--link" href="/Home/About">About</a>
                </li>

                @if (User.Identity.IsAuthenticated)
                {
                    <li class="header_menu-item">
                        <a class="header_menu-item--link" href="/Users/Index"> @User.Identity.Name </a>
                    </li>
                    <li class="header_menu-item">
                        <a class="header_menu-item--link" href="/HistoryBought/Index"> History </a>
                    </li>
                }
            </ul>
        </nav>
        @if (User.Identity.IsAuthenticated)
        {
            <div class="header_buttons">
                <a class="header_buttons-basket" href="/Cart/Index">
                    <img src="~/img/icon/basket.svg" alt="">
                </a>
                <a class="header_buttons-login" href="/Account/LogOff">
                    <span>Logout</span>
                </a>
            </div>
        }

      
    </div>
</header>

<div class="login-page container">
    <div class="form-wrapper ">
        <div class="form-wrapper_title-block">
            <span class="form-wrapper_title-text">Edit</span>
        </div>
        <form class="form-block" id="signup-form" method="post" asp-action="Index" asp-controller="Users">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email"
                       type="email"
                       class="form-group-input"
                       name="Email"
                       value="@Model.Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">Name</label>
                <input asp-for="FirstName"
                       type="text"
                       class="form-group-input"
                       name="FirstName"
                       placeholder="Name"
                       value="@Model.FirstName" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Surname</label>
                <input asp-for="LastName"
                       type="text"
                       class="form-group-input"
                       name="LastName"
                       placeholder="Surname"
                       value="@Model.LastName" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <input type="submit" class="form-group-button" value="Edit →" />
        </form>
        <div class="registration-block">
            <span class="registration-text">
                You want to change your password ?
            </span>
            <a class="registration-link"
               href="@Url.Action("ChangePassword", "Users", new { id = Model.Id })">
                Change Password
            </a>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container footer-wrapper">
        <div class=" main_block-header1 footer-logotype">
            WeGo
        </div>
        <div class="footer-menu">
            <div class="footer-title">Links</div>
            <nav class="footer-menu-nav">
                <ul>
                    <li>
                        <a href="#">Tickets</a>
                    </li>
                    <li>
                        <a href="#">Special</a>
                    </li>
                    
                    <li>
                        <a href="#">About</a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="footer-contact">
            <div class="footer-title">Contact</div>
            <div class="footer-contact-wrapper">
                <a class="footer-contact-col-line" target="_blank" href="tel:+380931234567">+380931234567</a>
                <a class="footer-contact-col-line" target="_blank" href="test@gmail.com">test@gmail.com</a>

            </div>
        </div>
        <div class="footer-socials">
            <div class="footer-title">Socials</div>
            <div class="footer-socials-wrapper">
                <a href="#" title="Facebook"
                   class="footer-socials-item"
                   target="_blank">
                    @* <img src="" class="footer_socials-item--image" alt="Facebook"> *@
                </a>
                <a href="#" title="Twitter" class="footer-socials-item" target="_blank">
                    @* <img src="" class="footer_socials-item--image" alt="Twitter"> *@
                </a>
                <a href="#" title="Instagram" class="footer-socials-item" target="_blank">
                    @* <img src="" class="footer_socials-item--image" alt="Twitter"> *@
                </a>
            </div>
        </div>
    </div>
</footer>